mydata <- read.csv("C:/Users/rvaro/Desktop/mydata.csv")
ncol(mydata)
nrow(mydata)
mean(mydata$q1)
plot(mydata$name, mydata$q1, pch='15')
plot(mydata$q1, mydata$name, pch=15, xlab='cholesterol', ylab='people', type='l' main='people and cholesterol')
max(mydata$q1)
min(mydata$q1)
mean(mydata$q1)
head(mydata)
head(mydata, 5)
names(mydata)
table(mydata$q2)
table(mydata$q3)
hist(mydata$q)
